version: '3'

services:
  db:
    image: postgres:14.9
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
