version: '3'

services:
  db:
    image: postgres:14.9
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.14-alpine
    restart: always

  app:
    image: nextcloud:27.1.2-apache
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      NEXTCLOUD_ADMIN_USER: andmi
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: example

volumes:
  nextcloud:
  db_data: